version: "3.9"

services:
  db:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: records
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
  
  server:
    build: server
    ports:
      - "3000:3000"

volumes:
  db-data: